import importlib.util
import sys
import tempfile
import types
from pathlib import Path

from PIL import Image


with tempfile.TemporaryDirectory() as temporary_directory:
    sys.modules["folder_paths"] = types.SimpleNamespace(
        get_output_directory=lambda: temporary_directory
    )
    module_path = Path(__file__).resolve().parents[1] / "nodes_speech_bubble.py"
    spec = importlib.util.spec_from_file_location("speech_bubble_sfx_test", module_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    layout = {
        "version": 1,
        "elements": [
            {
                "id": "sfx-1",
                "type": "sfx",
                "asset_id": "don-exclamation-mask",
                "x": 48,
                "y": 32,
                "w": 256,
                "h": 256,
                "rotation": 12,
                "opacity": 0.8,
                "visible": True,
            },
            {
                "id": "sfx-don",
                "type": "sfx",
                "asset_id": "don-exclamation-mask",
                "x": 330,
                "y": 30,
                "w": 150,
                "h": 140,
                "fill": "#22cc88",
                "stroke": "#241244",
                "stroke_width": 26,
                "visible": True,
            },
            {
                "id": "sfx-deru",
                "type": "sfx",
                "asset_id": "deru-small-tsu-mask",
                "x": 40,
                "y": 300,
                "w": 150,
                "h": 180,
                "fill": "#ffd42a",
                "stroke": "#111111",
                "stroke_width": 3,
                "visible": True,
            },
            {
                "id": "sfx-sweat",
                "type": "sfx",
                "asset_id": "sweat-glossy",
                "x": 300,
                "y": 300,
                "w": 150,
                "h": 150,
                "visible": True,
            },
        ],
    }
    rendered = module._render_layer(512, 512, layout, "", 2)
    alpha = rendered.getchannel("A")

    assert rendered.size == (512, 512)
    assert alpha.getbbox() is not None
    assert 0 < alpha.getextrema()[1] <= 255
    assert all(Path(path).is_file() for path in module._SFX_ASSETS.values())
    assert len(module._SFX_ASSETS) >= 4
    assert len(module._MASK_SFX_ASSETS) >= 2
    assert {"sweat-glossy", "sweat-flying"}.issubset(module._SFX_ASSETS)
    assert not {"sweat-glossy", "sweat-flying"}.intersection(module._MASK_SFX_ASSETS)
    variable_size_masks = {
        "rarity-crown-ssr-gold",
        "rarity-crown-sr-silver",
        "rarity-crown-r-red",
        "rarity-crown-n-green",
        "rarity-ribbon-super-rare-gold",
        "rarity-ribbon-very-rare-silver",
        "rarity-ribbon-rare-red",
        "rarity-ribbon-normal-green",
        "crown_ssr_gold",
        "crown_sr_silver",
        "crown_r_red",
        "crown_n_green",
        "ribbon_super_rare_gold",
        "ribbon_very_rare_silver",
        "ribbon_rare_red",
        "ribbon_normal_green",
        "arrow-curved-right-mask",
        "au-small-tsu-mask",
        "baki-mask",
        "ban-mask",
        "bubyuu-vertical-gpt-v1",
        "breath-puff-mask",
        "burun-katakana-small-tsu-mask",
        "burun-small-tsu-mask",
        "damee-mask",
        "dizzy-spiral-mask",
        "doka-mask",
        "dokun-small-tsu-mask",
        "dokkunn-vertical-gpt-v1",
        "chiro-vertical-uniform-mask",
        "upu-vertical-uniform-mask",
        "chuu-vertical-uniform-mask",
        "boto-small-tsu-vertical-uniform-mask",
        "dochu-vertical-uniform-mask",
        "don-exclamation-mask",
        "e-small-tsu-question-mask",
        "emphasis-lines-mask",
        "gashaan-mask",
        "hot-spring-mask",
        "iccha-mask",
        "iee-small-tsu-mask",
        "igu-small-tsu-mask",
        "ii-small-tsu-mask",
        "jaan-mask",
        "kaha-small-tsu-mask",
        "lightning-zap-mask",
        "moo-long-small-tsu-mask",
        "motion-swish-mask",
        "music-notes-mask",
        "nichaa-mask",
        "nani-kore-horizontal-gpt-v1",
        "naisho-horizontal-gpt-v1",
        "ikisou-horizontal-gpt-v1",
        "joo-vertical-gpt-v1",
        "gokkun-vertical-gpt-v1",
        "pushaa-vertical-gpt-v1",
        "chira-vertical-gpt-v1",
        "woo-vertical-gpt-v1",
        "rerorero-vertical-gpt-v1",
        "haa-katakana-vertical-gpt-v1",
        "dokkunn-hiragana-vertical-gpt-v1",
        "oke-mask",
        "parin-mask",
        "purun-small-tsu-mask",
        "shock-lines-mask",
        "shu-mask",
        "sleep-zzz-mask",
        "sparkle-radiant-mask",
        "tehepero-mask",
        "tension-lines-mask",
        "u-dakuten-long-small-tsu-mask",
        "uguuu-ellipsis-mask",
        "viin-mask",
        "worry-squiggle-mask",
        "yadaa-mask",
        "biku-hiragana-mask",
        "gyu-katakana-mask",
        "piku-mask",
        "kunekune-mask",
        "sawasawa-mask",
        "jupu-mask",
        "nyuru-mask",
        "buchupon-mask",
        "chupun-mask",
        "chupon-mask",
        "chupachupa-mask",
        "pichapicha-mask",
        "pan-small-tsu-mask",
        "topo-small-tsu-mask",
        "an-katakana-small-tsu-mask",
        "haa-long-small-tsu-mask",
        "faaa-small-tsu-mask",
        "tapun-small-tsu-mask",
        "a-small-tsu-mask",
        "an-hiragana-mask",
        "gyupu-mask",
        "buchupo-small-tsu-mask",
        "haa-mask",
        "haa-small-tsu-mask",
        "ipu-small-tsu-mask",
        "dobyuu-small-tsu-mask",
        "gori-small-tsu-mask",
        "deru-small-tsu-mask",
        "aha-small-tsu-mask",
        "aha-katakana-small-tsu-mask",
        "hachun-small-tsu-mask",
        "n-small-tsu-ellipsis-mask",
        "u-small-tsu-ellipsis-mask",
        "iccha-mask",
        "ii-small-tsu-mask",
        "uguuu-ellipsis-mask",
        "viin-mask",
        "nichaa-mask",
        "arrow-curved-right-mask",
        "baki-mask",
        "ban-mask",
        "breath-puff-mask",
        "dizzy-spiral-mask",
        "doka-mask",
        "don-exclamation-mask",
        "emphasis-lines-mask",
        "gashaan-mask",
        "hot-spring-mask",
        "jaan-mask",
        "lightning-zap-mask",
        "motion-swish-mask",
        "music-notes-mask",
        "parin-mask",
        "shock-lines-mask",
        "shu-mask",
        "sleep-zzz-mask",
        "sparkle-radiant-mask",
        "shii-horizontal-gpt-v1",
        "sore-dame-horizontal-gpt-v1",
        "worry-squiggle-mask",
        "au-small-tsu-mask",
        "kaha-small-tsu-mask",
        "igu-small-tsu-mask",
        "tehepero-mask",
        "iee-small-tsu-mask",
        "oke-mask",
        "damee-mask",
        "u-dakuten-long-small-tsu-mask",
        "moo-long-small-tsu-mask",
        "e-small-tsu-question-mask",
        "yadaa-mask",
        "burun-katakana-small-tsu-mask",
        "burun-small-tsu-mask",
        "purun-small-tsu-mask",
    }
    for path in module._SFX_ASSETS.values():
        with Image.open(path) as asset:
            asset_id = Path(path).stem
            if asset_id not in variable_size_masks and asset_id not in module._MASK_SFX_ASSETS:
                assert asset.size == (512, 512)
            else:
                assert asset.width > 0 and asset.height > 0
            assert "A" in asset.getbands()
            assert asset.getchannel("A").getpixel((0, 0)) == 0
    expected_mask_assets = {
        "don-exclamation-mask",
        "ban-mask",
        "doka-mask",
        "baki-mask",
        "gashaan-mask",
        "jaan-mask",
        "parin-mask",
        "shu-mask",
        "exclamation-mask",
        "question-mask",
        "dakuten-mask",
        "small-tsu-mask",
        "punpun-mask",
        "jii-mask",
        "wakuwaku-mask",
        "mochimochi-mask",
        "mushamusha-mask",
        "mogumogu-mask",
        "zuruzuru-mask",
        "gyuu-mask",
        "nadenade-mask",
        "dokidoki-mask",
        "kirakira-mask",
        "fuwafuwa-mask",
        "pyonpyon-mask",
        "anger-mark-mask",
        "brush-exclamation-mask",
        "brush-question-mask",
        "brush-heart-mask",
        "biku-katakana-mask",
        "biku-hiragana-mask",
        "bikun-mask",
        "zokuzoku-mask",
        "gyu-katakana-mask",
        "katakata-mask",
        "dokidoki-katakana-mask",
        "gugu-mask",
        "piku-mask",
        "hiku-mask",
        "rerorero-mask",
        "kunekune-mask",
        "sawasawa-mask",
        "taputapu-mask",
        "jupu-mask",
        "nyuru-mask",
        "buchu-mask",
        "buchu-small-tsu-mask",
        "buchupon-mask",
        "chu-small-tsu-mask",
        "chupu-mask",
        "chupu-small-tsu-mask",
        "chupun-mask",
        "chupo-mask",
        "chupon-mask",
        "chupa-mask",
        "chupachupa-mask",
        "puchu-mask",
        "puchu-small-tsu-mask",
        "puchun-mask",
        "nuchu-mask",
        "nupu-mask",
        "nupu-small-tsu-mask",
        "picha-mask",
        "pichapicha-mask",
        "kapu-mask",
        "kapu-small-tsu-mask",
        "pan-small-tsu-mask",
        "topo-small-tsu-mask",
        "an-katakana-small-tsu-mask",
        "haa-long-small-tsu-mask",
        "faaa-small-tsu-mask",
        "tapun-small-tsu-mask",
        "a-small-tsu-mask",
        "an-hiragana-mask",
        "gyupu-mask",
        "buchupo-small-tsu-mask",
        "haa-mask",
        "haa-small-tsu-mask",
        "ipu-small-tsu-mask",
        "dobyuu-small-tsu-mask",
        "aha-small-tsu-mask",
        "aha-katakana-small-tsu-mask",
        "hachun-small-tsu-mask",
        "n-small-tsu-ellipsis-mask",
        "u-small-tsu-ellipsis-mask",
        "iccha-mask",
        "ii-small-tsu-mask",
        "uwaaa-small-tsu-mask",
        "oo-dakuten-small-tsu-mask",
        "iguuu-mask",
        "gori-small-tsu-mask",
        "deru-small-tsu-mask",
        "dokun-small-tsu-mask",
        "uguuu-ellipsis-mask",
        "viin-mask",
        "nichaa-mask",
        "au-small-tsu-mask",
        "kaha-small-tsu-mask",
        "igu-small-tsu-mask",
        "tehepero-mask",
        "iee-small-tsu-mask",
        "oke-mask",
        "damee-mask",
        "u-dakuten-long-small-tsu-mask",
        "moo-long-small-tsu-mask",
        "e-small-tsu-question-mask",
        "yadaa-mask",
        "filled-heart-mask",
        "handdrawn-filled-heart-mask",
        "giri-small-tsu-vertical-mask",
        "nuron-angular-vertical-mask",
        "dochu-exclamation-angular-vertical-mask",
        "chiro-vertical-uniform-mask",
        "upu-vertical-uniform-mask",
        "chuu-vertical-uniform-mask",
        "boto-small-tsu-vertical-uniform-mask",
        "dochu-vertical-uniform-mask",
        "giu-long-angular-vertical-mask",
        "hiku-small-tsu-angular-vertical-mask",
        "giu-angular-vertical-mask",
        "zuru-angular-vertical-mask",
        "dokun-hiragana-angular-vertical-mask",
        "dokun-hiragana-angular-horizontal-mask",
        "zubu-small-tsu-angular-vertical-mask",
        "dokkunn-vertical-gpt-v1",
        "bubyuu-vertical-gpt-v1",
        "sore-dame-horizontal-gpt-v1",
        "nani-kore-horizontal-gpt-v1",
        "shii-horizontal-gpt-v1",
        "naisho-horizontal-gpt-v1",
        "ikisou-horizontal-gpt-v1",
        "joo-vertical-gpt-v1",
        "gokkun-vertical-gpt-v1",
        "pushaa-vertical-gpt-v1",
        "chira-vertical-gpt-v1",
        "woo-vertical-gpt-v1",
        "rerorero-vertical-gpt-v1",
        "haa-katakana-vertical-gpt-v1",
        "dokkunn-hiragana-vertical-gpt-v1",
        "burun-katakana-small-tsu-mask",
        "burun-small-tsu-mask",
        "purun-small-tsu-mask",
        "suit-club-mask",
        "arrow-thick-right-mask",
        "arrow-thin-right-mask",
        "arrow-handdrawn-right-mask",
        "arrow-curved-right-mask",
        "arrow-wavy-right-mask",
        "arrow-loop-mask",
        "arrow-double-mask",
        "star-outline-mask",
        "star-filled-mask",
        "sparkle-four-mask",
        "sparkle-cluster-mask",
        "sparkle-radiant-mask",
        "rough-circle-mask",
        "rough-double-circle-mask",
        "scribble-ball-mask",
        "scribble-circle-loose-mask",
        "scribble-circle-oval-mask",
        "scribble-circle-heavy-mask",
        "scribble-circle-knot-mask",
        "rough-underline-mask",
        "anger-mark-small-mask",
        "sweat-drop-mask",
        "sweat-drops-mask",
        "emphasis-lines-mask",
        "shock-lines-mask",
        "tension-lines-mask",
        "worry-squiggle-mask",
        "breath-puff-mask",
        "dizzy-spiral-mask",
        "hot-spring-mask",
        "bandage-mask",
        "music-notes-mask",
        "sleep-zzz-mask",
        "lightning-zap-mask",
        "motion-swish-mask",
        "gyuu-reference-vertical-mask",
        "pito-reference-vertical-mask",
        "norun-reference-vertical-mask",
        "kuu-reference-vertical-mask",
        "ki-katakana-reference-vertical-mask",
        "munyu-reference-vertical-mask",
        "piyo-reference-vertical-mask",
        "nuri-small-tsu-reference-vertical-mask",
        "oga-reference-vertical-mask",
        "oa-exclamation-reference-vertical-mask",
        "nuru-small-tsu-reference-vertical-mask",
        "boyon-reference-vertical-mask",
        "byon-katakana-reference-vertical-mask",
        "zucha-reference-vertical-mask",
        "sucha-reference-vertical-mask",
        "byuu-long-reference-vertical-mask",
        "goku-reference-vertical-mask",
        "doku-small-tsu-katakana-reference-vertical-mask",
        "haga-small-tsu-reference-vertical-mask",
    }
    assert expected_mask_assets.issubset(module._MASK_SFX_ASSETS)

    def render_raster_outline(stroke_width):
        return module._render_layer(
            512,
            320,
            {
                "version": 1,
                "elements": [
                    {
                        "id": "rarity-outline-test",
                        "type": "sfx",
                        "asset_id": "rarity-ribbon-normal-green",
                        "x": 110,
                        "y": 90,
                        "w": 198,
                        "h": 105,
                        "stroke": "#ffffff",
                        "stroke_width": stroke_width,
                        "visible": True,
                    }
                ],
            },
            "",
            1,
        )

    plain_bbox = render_raster_outline(0).getchannel("A").getbbox()
    outlined_bbox = render_raster_outline(6).getchannel("A").getbbox()
    assert plain_bbox is not None and outlined_bbox is not None
    assert outlined_bbox[0] < plain_bbox[0]
    assert outlined_bbox[1] < plain_bbox[1]
    assert outlined_bbox[2] > plain_bbox[2]
    assert outlined_bbox[3] > plain_bbox[3]

print("sfx stamp rendering: pass")
