"""Regenerate narrow Japanese SFX masks with a heavier brush-lettered treatment."""

from __future__ import annotations

import random
import re
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
HTML_PATH = ROOT / "web" / "speech-bubble-editor.html"
ASSET_DIR = ROOT / "web" / "assets" / "sfx"
FONT_PATH = Path(r"C:\Windows\Fonts\HGRGY.TTC")
FONT_INDEX = 1  # HGP行書体
CANVAS_SIZE = 512
VERTICAL_COMPRESSION = 0.82

# Keep these readable narrow presets compact without changing their output box.
# The transparent top/bottom padding is intentional: ComfyUI resizes the full
# asset to the stored layer box, so cropping it away would undo the compression.
VERTICAL_COMPRESSION_IDS = {
    "pan-small-tsu-mask",
    "topo-small-tsu-mask",
    "an-katakana-small-tsu-mask",
    "haa-long-small-tsu-mask",
    "faaa-small-tsu-mask",
    "tapun-small-tsu-mask",
    "a-small-tsu-mask",
    "an-hiragana-mask",
    "gyupu-mask",
    "buchupo-small-tsu-mask",
    "haa-mask",
    "haa-small-tsu-mask",
    "ipu-small-tsu-mask",
    "dobyuu-small-tsu-mask",
    "hachun-small-tsu-mask",
    "u-small-tsu-ellipsis-mask",
    "iccha-mask",
    "ii-small-tsu-mask",
}

# These are Japanese SFX whose current content is either visibly thin or was
# generated by the narrow 320x512 template. Deliberately leave broad horizontal
# SFX and the established aha reference untouched.
TARGET_IDS = (
    "biku-hiragana-mask",
    "gyu-katakana-mask",
    "piku-mask",
    "kunekune-mask",
    "sawasawa-mask",
    "jupu-mask",
    "nyuru-mask",
    "buchupon-mask",
    "chupun-mask",
    "chupon-mask",
    "chupachupa-mask",
    "pichapicha-mask",
    "pan-small-tsu-mask",
    "topo-small-tsu-mask",
    "an-katakana-small-tsu-mask",
    "haa-long-small-tsu-mask",
    "faaa-small-tsu-mask",
    "tapun-small-tsu-mask",
    "a-small-tsu-mask",
    "an-hiragana-mask",
    "gyupu-mask",
    "buchupo-small-tsu-mask",
    "haa-mask",
    "haa-small-tsu-mask",
    "ipu-small-tsu-mask",
    "dobyuu-small-tsu-mask",
    "gori-small-tsu-mask",
    "deru-small-tsu-mask",
    "hachun-small-tsu-mask",
    "n-small-tsu-ellipsis-mask",
    "u-small-tsu-ellipsis-mask",
    "iccha-mask",
    "ii-small-tsu-mask",
    "uguuu-ellipsis-mask",
    "au-small-tsu-mask",
    "kaha-small-tsu-mask",
    "igu-small-tsu-mask",
    "tehepero-mask",
    "iee-small-tsu-mask",
    "oke-mask",
    "damee-mask",
    "u-dakuten-long-small-tsu-mask",
    "moo-long-small-tsu-mask",
    "e-small-tsu-question-mask",
    "yadaa-mask",
)


def preset_labels() -> dict[str, str]:
    labels: dict[str, str] = {}
    pattern = re.compile(r'\{id:"([^"]+)",label:"([^"]+)"')
    for line in HTML_PATH.read_text(encoding="utf-8").splitlines():
        match = pattern.search(line)
        if match:
            labels[match.group(1)] = match.group(2)
    missing = [asset_id for asset_id in TARGET_IDS if asset_id not in labels]
    if missing:
        raise RuntimeError(f"Missing preset labels: {', '.join(missing)}")
    return labels


def glyph_alpha(char: str, font_size: int) -> Image.Image:
    font = ImageFont.truetype(str(FONT_PATH), font_size, index=FONT_INDEX)
    probe = Image.new("L", (font_size * 3, font_size * 3), 0)
    draw = ImageDraw.Draw(probe)
    stroke = max(2, round(font_size * 0.035))
    box = draw.textbbox((0, 0), char, font=font, stroke_width=stroke)
    if box[2] <= box[0] or box[3] <= box[1]:
        return Image.new("L", (1, 1), 0)
    layer = Image.new("L", (box[2] - box[0] + 24, box[3] - box[1] + 24), 0)
    ImageDraw.Draw(layer).text(
        (12 - box[0], 12 - box[1]),
        char,
        font=font,
        fill=255,
        stroke_width=stroke,
        stroke_fill=255,
    )
    bbox = layer.getbbox()
    return layer.crop(bbox) if bbox else Image.new("L", (1, 1), 0)


def render_vertical(asset_id: str, text: str) -> Image.Image:
    chars = list(text)
    count = len(chars)
    gap = max(5, min(11, 18 - count * 2))
    usable_height = 452 - gap * max(0, count - 1)
    factors = [1.25 - 0.50 * (index / max(1, count - 1)) for index in range(count)]
    base_height = usable_height / sum(factors)
    rng = random.Random(asset_id)
    canvas = Image.new("L", (CANVAS_SIZE, CANVAS_SIZE), 0)
    y = 30

    for index, char in enumerate(chars):
        factor = factors[index]
        target_h = max(18, round(base_height * factor))
        glyph = glyph_alpha(char, max(96, round(target_h * 2.35)))
        aspect = glyph.width / max(1, glyph.height)
        x_scale = 1.24 - 0.20 * (index / max(1, count - 1))
        target_w = max(14 if char in ".。,、" else 30, round(target_h * aspect * x_scale))
        target_w = min(target_w, CANVAS_SIZE - 48)
        glyph = glyph.resize((target_w, target_h), Image.Resampling.LANCZOS)

        angle = rng.uniform(-5.5, 5.5) + (2.0 if index == 0 else 0.0)
        glyph = glyph.rotate(angle, resample=Image.Resampling.BICUBIC, expand=True)
        x = round((CANVAS_SIZE - glyph.width) / 2 + rng.uniform(-10, 10))
        x = max(18, min(CANVAS_SIZE - glyph.width - 18, x))
        canvas.paste(glyph, (x, y), glyph)
        y += target_h + gap

    bbox = canvas.getbbox()
    if not bbox:
        raise RuntimeError(f"Generated empty mask for {asset_id}: {text}")
    margin = 18
    left = max(0, bbox[0] - margin)
    top = max(0, bbox[1] - margin)
    right = min(CANVAS_SIZE, bbox[2] + margin)
    bottom = min(CANVAS_SIZE, bbox[3] + margin)
    cropped = canvas.crop((left, top, right, bottom))
    return Image.merge("RGBA", (Image.new("L", cropped.size, 255),) * 3 + (cropped,))


def compress_vertical(image: Image.Image) -> Image.Image:
    compressed_height = max(1, round(image.height * VERTICAL_COMPRESSION))
    compressed = image.resize((image.width, compressed_height), Image.Resampling.LANCZOS)
    output = Image.new("RGBA", image.size, (255, 255, 255, 0))
    output.alpha_composite(compressed, (0, (image.height - compressed_height) // 2))
    return output


def main() -> None:
    if not FONT_PATH.exists():
        raise FileNotFoundError(FONT_PATH)
    labels = preset_labels()
    for asset_id in TARGET_IDS:
        image = render_vertical(asset_id, labels[asset_id])
        if asset_id in VERTICAL_COMPRESSION_IDS:
            image = compress_vertical(image)
        output = ASSET_DIR / f"{asset_id}.webp"
        image.save(output, "WEBP", lossless=True, method=6)
        print(f"{asset_id}: {labels[asset_id]} -> {image.width}x{image.height}")


if __name__ == "__main__":
    main()
